spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=TESTDB;
    username: sqlserver
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    show-sql: true
    hibernate:
      ddl-auto: update
openapi:
  info:
    server: http://localhost:8080
    termsOfService: http://swagger.io/terms/