spring:
  profiles:
    active: @activatedProperties@
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  application:
    name: mbb-assignment-service
  banner:
    location: classpath:static/banner/banner.txt
  messages:
    basename: messages/messages
    cache-seconds: -1
    encoding: UTF-8
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-ui.html
info:
  application:
    name: "mbb-assignment-service"
    description: "MBB Assignment Service"
    groupId: "com.mbb.assignment"
    artifactId: "mbb-assignment-service"
    version: "1"
openapi:
  info:
    title: "MBB Assignment Service API"
    version: "v_1.0"
    ownerName: "Teh Fu Hau"
    ownerEmail: "little940301@gmail.com"
    licenseName: "Apache 2.0"
    licenseUrl: "http://www.apache.org/licenses/LICENSE-2.0.html"